### PR TITLE
Changed WorldMapWalker to walk when not moving, instead of idle

### PR DESCRIPTION
**Pull request by futureproof123**
Changed WorldMapWalker to walk when not moving, instead of idle

### CODE REVIEW

**Comment by zeruth** [comment]
remove the actions stuff please

**Comment by futureproof123** [comment]
> remove the actions stuff please

I'm not sure how lol 😂

**Comment by tilkinsc** [comment]
Use `git rm [file]` on the files you added. You did `git add` on the files or intellij is configured to automatically add new files. Then do a commit and push. The latest commit here should show the deletion (untracking) of the files. It doesn't delete your files locally.

**Comment by tilkinsc** [comment]
It seems like everything is ready for merging, you took care of the workflow directory files being added.

**Pull request merged**
