### PR TITLE
osrs: renaming

### PR DESCRIPTION
**Pull request by DD33LLTTAA**
Numerous unrenamed fields, methods, and classes have been renamed to accurately describe their purpose

### CODE REVIEW

**Comment by zeruth** [comment]
I love the work, and I really hate to be this guy right now....

In order for me to merge this, it will have to be done again against the current osrs module in main.

The project just went through a major injector change, and at the same time, I fixed osrs' bytecode and removed all multipliers.

If I were to merge this right now, I would be re-introducing bad bytecode and multipliers that no longer exist. The OSRS module is now the injection target, and it has to be 100% valid

**Comment by DD33LLTTAA** [comment]
Hi @zeruth - I actually started this PR earlier this afternoon after the major changes you referred to (the OSRS module being the injection target) were in `main`, so we *might* be in the clear.

However, doing my renamings did seem to cause some issues when running (so it's good we're holding off!). I've provided a [snippet](https://gist.github.com/DD33LLTTAA/1da3495603d6edd5b15347670eaa1a0f) of the issues I see now - I have an idea of how to resolve them (save for the `LongNode` warning), but I think some of the resolutions I would need to perform would need your blessing beforehand.

As evidenced by the above snippet, there does seem to be a few issues pertaining to some further upstream methods expecting references to un-renamed methods - not sure if I should revert my changes to these, or go ahead and keep the renaming I've performed and adjust the renaming upstream. 

Curious to hear your thoughts!

**Comment by zeruth** [comment]
Yes, my apologies, after reviewing some code in main, We identified a bug in the deob that is still allowing some folding to remain (ends up being *1 so no harm at all)

I don't care about any text being changed in Import annotations in api-rs so feel free to do that all you want. try not to change method names/sigs in api/api-rs though.

Everything is automatically exported as its field / method name to the injector, as such, naming/signature matters. keep that in mind

**Comment by zeruth** [comment]
Also, as a note, renaming anything in ClientPackets or Buffer means the deob will have to be ran through https://github.com/MeteorLite/osrs-packet-decoder again to generate the api classes / jsons (unless you change all that manually, which I wouldn't advise

**Comment by DD33LLTTAA** [comment]
Hey @zeruth - just pushed up some changes! Appreciate you mentioning you'll take care of the Buffer methods this time around :)

I did modify a few `@Import` annotations in `api` and `api-rs` and renamed the associated methods (just for clarity) - do these pose an issue? They're tied to fields on the client that I modified.
image

Additionally, here are the console logs from when I run everything:
```
> Task :injector:inject
[Injector]                Java8Ifier finished in 8.189 ms
[Injector]                CreateAnnotations finished in 7.722 ms
[Injector]                CopyRuneLiteClasses finished in 68.64 μs
[Injector]                RuneLiteIterables finished in 805.9 μs
[Injector]                RuneliteObject finished in 74.10 μs
[Injector]                [DEBUG] Class LongNode implements nonexistent interface net/runelite/rs/api/RSLongNode, skipping interface injection
[Injector]                InterfaceInjector finished in 11.22 ms
[Injector]                RasterizerAlpha finished in 801.2 ms
[Injector]                InjectHook finished in 1.895 s
[Injector]                InjectHookMethod finished in 7.794 ms
[Injector]                MixinInjector finished in 2.053 s
[Injector]                InjectConstruct finished in 2.036 ms
[Injector]                RSApiInjector finished in 37.23 ms
[Injector]                ScriptVM finished in 9.333 ms
[Injector]                ClearColorBuffer finished in 4.099 ms
[Injector]                RenderDraw finished in 495.9 μs
[Injector]                Occluder finished in 64.42 μs
[Injector]                DrawMenu finished in 1.649 ms
[Injector]                GameDrawingMode finished in 147.0 μs
[Injector]                AddPlayerToMenu finished in 344.3 μs
[Injector]                RuneliteMenuEntry finished in 404.5 μs
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.readUByteAdd()I
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.readUByteNeg()I
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.readUByteSub()I
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.readByteAdd()B
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.readByteNeg()B
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.readByteSub()B
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.writeShortAdd(I)V
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.writeShortAddLE(I)V
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.readUShortLE()I
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.readUShortAdd()I
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.readShortAddLE()I
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.writeByteAdd(I)V
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.writeByteSub(I)V
[Validator]               Class Buffer implements interface net/runelite/rs/api/RSBuffer but doesn't implement net/runelite/rs/api/RSBuffer.writeByteNeg(I)V
[Validator]               RSApiValidator completed. Status [ERROR] 1655 overridden methods, 14 missing
[Injector]                SourceChanger finished in 717.6 μs
[Injector]                Injected 287 class interfaces
[Injector]                Injected 9 mixin interfaces
[Injector]                Injected 107 mixin fields
[Injector]                Shadowed 104 fields
[Injector]                Injected 955, copied 72, replaced 78 methods
[Injector]                Injected 334 field hooks.
[Injector]                Injected 54 method hooks
[Injector]                Injected 23 constructors
[Injector]                Injected 1006 getters, 353 setters, and 188 invokers
```

Let me know how everything looks! If you have any further comments, I'd be more than happy to incorporate them in!

**Pull request merged**
